version: '3.8'

# change services.[*].image value as needed for container orchastration solution

services:
    nginx:
        image: docker.io/library/nginx:1.25.1
        networks:
            - internal
        ports:
            - 8080:80
        volumes:
            - ./services/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./services/nginx/var/log/nginx/:/var/log/nginx/
            - ./services/shared/var/www/html/:/var/www/html/
        links:
            - php
    php:
        build:
            context: .
            dockerfile: ./services/php/Containerfile
        networks:
            - internal
        volumes:
            # - ./services/php/tmp/:/tmp/
            - ./services/php/usr/local/etc/php-fpm.d/php_flame_graph.conf:/usr/local/etc/php-fpm.d/php_flame_graph.conf
            - ./services/php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./services/php/var/log/php/:/var/log/php/
            - ./services/shared/var/www/html/:/var/www/html/
        user: root
networks:
  internal:
    driver: bridge
