version: '3.8'

services:
    nginx:
        image: docker.io/library/nginx:1.25.3 # change as desired to pull from different source registry
        networks:
            - internal
        ports:
            - 8080:80
        volumes:
            - ./services/app/:/var/www/html/
            # TODO do we need this or will the default nginx configuration work?
            - ./services/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            # To read the logs from outside the container
            - ./services/nginx/var/log/nginx/:/var/log/nginx/
        links:
            - php
    php:
        build:
            context: .
            dockerfile: ./services/php/Containerfile
        networks:
            - internal
        # Enables connectivity to the xDebug process running inside the container
        # ports:
        #     - 9003:9003
        volumes:
            - ./services/app/:/var/www/html/            
            - ./services/php/usr/local/etc/php-fpm.d/php_flame_graph.conf:/usr/local/etc/php-fpm.d/php_flame_graph.conf
            - ./services/php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./services/php/var/log/php/:/var/log/php/
    php_cli:
        command: tail -f /dev/null
        image: docker.io/library/php:8.3 # change as desired to pull from different source registry
        volumes:
            - ./services/app/:/var/www/html/
            - ./services/php_cli/var/log/php/:/var/log/php/
networks:
  internal:
    driver: bridge
