version: '3.8'

services:
    nginx:
        image: docker.io/library/nginx:1.25.3 # change as desired to pull from different source registry
        networks:
            - internal
        ports:
            - 8080:80
        volumes:
            # TODO do we need this or will the default nginx configuration work?
            - ./services/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            # To read the logs from outside the container
            - ./services/nginx/var/log/nginx/:/var/log/nginx/
            # TODO is this needed in the Nginx service
            - ./services/shared/var/www/html/:/var/www/html/
        links:
            - php
        user: root
    php:
        build:
            context: .
            dockerfile: ./services/php/Containerfile
        networks:
            - internal
        volumes:
            # - ./services/php/tmp/:/tmp/
            - ./services/php/usr/local/etc/php-fpm.d/php_flame_graph.conf:/usr/local/etc/php-fpm.d/php_flame_graph.conf
            - ./services/php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./services/php/var/log/php/:/var/log/php/
            - ./services/shared/var/www/html/:/var/www/html/
        user: root
networks:
  internal:
    driver: bridge
